

MidiSynth : oscil.cpp
	g++ -Wall -D__MACOSX_CORE__ -std=c++11 -ljack oscil.cpp osc.h jack_module.cpp jack_module.h ./rtmidi-master/RtMidi.cpp -framework CoreMIDI -framework CoreAudio -framework CoreFoundation
